=== Testing the Persistence Layer
Now we will write some tests to verify that our persistence layer is working as expected.

==== Writing a Test
The basic structure of a repository layer test is:

. Create a new object.
. Save the object to the database using the repository.
. Read the object from the database using the repository.
. Assert that the object from the database has the correct attributes.

Use dependency injection (via the `@Autowired` annotation) to get an instance of your repository. Also add the `@Test` annotation to each test method.

You will want to clear the database after each run so that you don't waste storage space and avoid violating any unique constraints. Define a method `clearDatabase()` with the annotation `@AfterEach` that clears all relevant tables. *Make sure you clear your dependent classes prior to clearing your independent classes, as operations _only_ cascade if the associative relationship is a composition!*

The test class for the `PersonRepository` should be similar to the following code. The package and import statements have been omited for clarity.

```java 
package ca.mcgill.ecse321.EventRegistration.dao;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import ca.mcgill.ecse321.EventRegistration.models.Person;

@SpringBootTest
public class PersonRepositoryTests {
	@Autowired
	private PersonRepository personRepository;

	@AfterEach
	public void clearDatabase() {
		personRepository.deleteAll();
	}

	@Test
	public void testPersistAndLoadPerson() {
		// Create person.
		String name = "Muffin Man";
		Integer age = 40;
		String address = "123 Drury Lane";
		Person person = new Person();
		person.setName(name);
		person.setAge(age);
		person.setAddress(address);

		// Save person
		personRepository.save(person);

		// Read person from database.
		person = personRepository.findPersonByName(name);

		// Assert that person is not null and has correct attributes.
		assertNotNull(person);
		assertEquals(name, person.getName());
		assertEquals(age, person.getAge());
		assertEquals(address, person.getAddress());
	}
}
```

The test class for the `EventRepository` should look something like this:

```java
package ca.mcgill.ecse321.EventRegistration.dao;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.sql.Date;
import java.sql.Time;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import ca.mcgill.ecse321.EventRegistration.models.Event;

@SpringBootTest
public class EventRepositoryTests {
	@Autowired
	private EventRepository eventRepository;

	@AfterEach
	public void clearDatabase() {
		eventRepository.deleteAll();
	}

	@Test
	public void testPersistAndLoadEvent() {
		// Create event.
        String name = "Shrek 2";
		Date date = Date.valueOf("2023-12-01");
		Time start = Time.valueOf("08:00:00");
		Time end = Time.valueOf("12:00:00");

		Event event = new Event();
		event.setName(name);
		event.setDate(date);
		event.setStartTime(start);
		event.setEndTime(end);

		// Save event.
		eventRepository.save(event);

		// Read event from database.
		event = eventRepository.findEventByName(name);

		// Assert event is not null and has correct attributes.
		assertNotNull(event);
		assertEquals(name, event.getName());
		assertEquals(date, event.getDate());
		assertEquals(start, event.getStartTime());
		assertEquals(end, event.getEndTime());
	}
}
```

The test class for the `RegistrationRepository` should look something like this:
``` java
@package ca.mcgill.ecse321.EventRegistration.dao;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.sql.Date;
import java.sql.Time;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import ca.mcgill.ecse321.EventRegistration.models.Event;
import ca.mcgill.ecse321.EventRegistration.models.Person;
import ca.mcgill.ecse321.EventRegistration.models.Registration;

@SpringBootTest
public class RegistrationRepositoryTests {
	@Autowired
	private PersonRepository personRepository;
	@Autowired
	private EventRepository eventRepository;
	@Autowired
	private RegistrationRepository registrationRepository;

	@AfterEach
	public void clearDatabase() {
		registrationRepository.deleteAll();
		eventRepository.deleteAll();
		personRepository.deleteAll();
	}

	@Test
	public void testPersistAndLoadRegistration() {
		// Create and persist person.
        String personName = "Muffin Man";
		Integer personAge = 40;
		String personAddress = "123 Drury Lane";
		Person person = new Person();
		person.setName(personName);
		person.setAge(personAge);
		person.setAddress(personAddress);
		personRepository.save(person);

		// Create and persist event.
		String eventName = "Shrek 2";
		Date eventDate = Date.valueOf("2023-12-01");
		Time eventStart = Time.valueOf("08:00:00");
		Time eventEnd = Time.valueOf("12:00:00");
		Event event = new Event();
		event.setName(eventName);
		event.setDate(eventDate);
		event.setStartTime(eventStart);
		event.setEndTime(eventEnd);
		eventRepository.save(event);

		// Create registration.
		Registration registration = new Registration();
		registration.setPerson(person);
		registration.setEvent(event);

		// Save registration.
		registrationRepository.save(registration);

		// Read registration from database.
		registration = registrationRepository.findByPersonAndEvent(person, event);
		assertNotNull(registration);
		assertNotNull(registration.getId());
		assertEquals(person.getName(), registration.getPerson().getName());
		assertEquals(person.getAge(), registration.getPerson().getAge());
		assertEquals(person.getAddress(), registration.getPerson().getAddress());
		assertEquals(event.getName(), registration.getEvent().getName());
		assertEquals(event.getDate(), registration.getEvent().getDate());
		assertEquals(event.getStartTime(), registration.getEvent().getStartTime());
		assertEquals(event.getEndTime(), registration.getEvent().getEndTime());
	}
}

``` 

==== Running the Tests
To run the tests, `cd` into the `EventRegistration` folder and issue the command `./gradlew test`.


==== Debugging Failing Tests
You will almost certainly encounter failing tests at some point. When this happens, it is usually helpful to read the stack trace and see if there are any helpful hints. At first you will probably find that the stack traces are short and not very informative. Add the following snippet inside the `test` task in your `build.gradle` file:
```
testLogging {
	exceptionFormat "full"
	//...other configurations
}
```
Re-run the tests and you should see much longer stack traces with helpful hints. Focus on the "Caused by:" parts.

If _all_ the tests are failing (including `contextLoads()`), it means your project failed to start. This is generally because it failed to connect to the database or there is an issue with your model.

===== Common Errors
- Missing or badly-formatted data in `application.properties`. You need a database driver, the URL of an existing database, a username, and a password. The database URL is particularly easy to mess up: it needs to follow the format `jdbc:postgresql://localhost:port/database_name`.
- Using reserved keywords for class names (e.g., `User`). This will result in a nasty SQL syntax error.
- Incorrectly named repository methods. For example, if you have a property `eventName` and you call your repository method `findEventByName()`, Spring will complain that there's no property called `name` in the `Event` class.
- Missing annotations. For example, if you forget an `@Id` annotation, Spring will complain that there's no unique identifier for your class.
